# Generated by Django 5.2 on 2025-04-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvillageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='full_name',
            field=models.TextField(blank=True),
        ),
    ]
