# Generated by Django 5.2 on 2025-05-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvillageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpeg/*', upload_to='profile_pics/'),
        ),
    ]
