# Generated by Django 5.2 on 2025-05-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvillageapp', '0003_alter_user_phone_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='profile_pics/'),
        ),
    ]
